import "./globals.css"
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Header from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${GeistSans.className} antialiased min-h-screen flex flex-col`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<TooltipProvider>	
						<Header/>
						<div className="grow flex">
							{children}
						</div>
					</TooltipProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
