import Breadcrumbs from "@/components/app-breadcrumbs"
import AppForm from "@/components/app-form"
import { countries } from "@/data/countries"
import { genres } from "@/data/genres"
import { languages } from "@/data/languages"
import { Info, TextCursorInput } from "lucide-react"

export default function CreateNewSoundRecording() {
    const crumbs = [
        { title: "Dashboard", href: "/" },
        { title: "Catalog", href: "/catalog" },
        { title: "Sound Recordings", href: "/catalog/recordings" },
        { title: "Create Sound Recording", href: "/catalog/recordings/create", currentPage: true },
    ]
    const formModel = [
        {
            checked: true,
            description: "This is the title that will appear in stores",
            disabled: false,
            label: "Track Title",
            name: "name",
            placeholder: "",
            required: true,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Input",
            colSpan: 6,
            options: [],
        },
        {
            checked: true,
            description: "Indicates the mix version of the recording",
            disabled: false,
            label: "Mix Version",
            name: "version",
            placeholder: "Remastered 2025...",
            required: false,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Input",
            colSpan: 6,
            options: [],
        },
        {
            checked: true,
            description: "Must be in .wav format and less than 50MB",
            disabled: false,
            label: "Upload Audio File",
            name: "audio",
            placeholder: "",
            required: true,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Audio Upload",
            colSpan: 12,
            options: [],
        },
        {
            checked: true,
            description: "One will be generated for you if left blank",
            disabled: false,
            label: "Custom ISRC",
            name: "isrc",
            placeholder: "",
            required: false,
            rowIndex: 0,
            type: "isrc",
            value: "",
            variant: "Input",
            colSpan: 12,
            options: [],
        },
        {
            checked: true,
            description: "Country the recording was created",
            disabled: false,
            label: "Country of Recording",
            name: "country",
            placeholder: "",
            required: true,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Combobox",
            colSpan: 6,
            options: countries,
        },
        {
            checked: true,
            description: "Year the recording was created",
            disabled: false,
            label: "Year of Recording",
            name: "year",
            placeholder: "",
            required: true,
            rowIndex: 0,
            type: "number",
            value: "",
            variant: "Input",
            colSpan: 6,
            options: [],
        },
        {
            checked: true,
            description: "Primary genre of the recording",
            disabled: false,
            label: "Primary Genre",
            name: "genrePrimary",
            placeholder: "",
            required: true,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Combobox",
            colSpan: 6,
            options: genres,
        },
        {
            checked: true,
            description: "Secondary genre of the recording",
            disabled: false,
            label: "Secondary Genre",
            name: "genreSecondary",
            placeholder: "",
            required: true,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Input",
            colSpan: 6,
            options: [],
        },
        // {
        //     checked: true,
        //     description: "Secondary genre of the recording",
        //     disabled: false,
        //     label: "Secondary Genre",
        //     name: "genreSecondary",
        //     placeholder: "",
        //     required: true,
        //     rowIndex: 0,
        //     type: "",
        //     value: "",
        //     variant: "Combobox",
        //     colSpan: 6,
        //     options: genres,
        // },
        {
            checked: true,
            description: "Language of the recording (or specify instrumental)",
            disabled: false,
            label: "Language",
            name: "language",
            placeholder: "",
            required: true,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Combobox",
            colSpan: 6,
            options: languages,
        },
        {
            checked: true,
            description: "Indicates whether this recording contains explicit lyrics",
            disabled: false,
            label: "Contains Explicit Content",
            name: "explicit",
            placeholder: "",
            required: true,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Combobox",
            colSpan: 6,
            options: [{"name":"Yes","code":"yes"},{"name":"No","code": "no"}],
        },
        {
            checked: true,
            description: "Full text of song lyrics",
            disabled: false,
            label: "Lyrics",
            name: "lyrics",
            placeholder: "",
            required: false,
            rowIndex: 0,
            type: "",
            value: "",
            variant: "Textarea",
            colSpan: 12,
            options: [],
        },
    ]
    return (
        <>
            <Breadcrumbs crumbs={crumbs}/>
            <div className="h-16 border-b flex justify-between items-center pl-6">
                <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight">Create New Sound Recording</h2>
            </div>
            <div className="bg-blue-500/10 border-b border-blue-500/20 h-16 px-6 flex items-center gap-3 text-blue-500">
                <Info size={18}/>
                <span>You may not edit the ISRC code after it has been assigned.</span>
            </div>
            <AppForm model={formModel} api="/api/recordings/create" method="POST" redirectPath="/catalog/recordings" formPath="/catalog/recordings/create"/>
        </>
    )
}